[profile.default]
src = "src"
out = "out"
libs = ["lib"]
optimizer-runs = 10_000

compilation_restrictions = [
    { paths = "src/LoanManager.sol", optimizer_runs = 1_000 },
    { paths = "src/GeneralManager.sol", optimizer_runs = 1_000 },
]

fs_permissions = [
  { access = "read-write", path = "./addresses/tests/"},
  { access = "read-write", path = "./addresses/addresses-31337.json"},
  { access = "read-write", path = "./addresses/addresses-998.json"},
  { access = "read", path = "./script/artifacts/WHYPE9.json"}
]

[fmt]
tab_width = 2

[etherscan]
  hyperliquid = { key = "${API_KEY_ETHERSCAN}" }

[rpc_endpoints]
  hyperliquid = "https://rpc.hyperliquid.xyz/evm"
  hyperliquid-testnet = "https://rpc.hyperliquid-testnet.xyz/evm"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options